# Generated by Django 4.2.7 on 2023-12-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
